### ISSUE TITLE
Sencha Architect 3 - Ext.ux.AccordionList

### ISSUE THREAD

**Issue by biletooth** [kawanoshinobu/Ext.ux.AccordionList#29]
Can you explain how the store fields works in Sencha Architect 3? I can programmatically assign the store to the accordion component accordion.setStore(x); but i cannot seem to get the accordion to work with the store field. It seems that Sencha Architect 3 wraps the field in a ' '. 

store: 'Ext.create(\'App.data.TreeStore\')'

**Comment by shailendramonu** [comment]
Same problem here. any update on this? How do I make this thing work on architect?

**Comment by kawanoshinobu** [comment]
Hi there!

Could you confirm the description of "Integrate into Sencha Architect" at README.md?

You need to set store instance at initialize event handler because Architect does not support to use TreeStore at user extensions config.

**Comment by shailendramonu** [comment]
Tried:

var store = Ext.create('MyApp.store.Task');
store.load();

----------------

var store = Ext.create('Ext.data.TreeStore', {
      model: 'MyApp.model.Task',
      defaultRootProperty: 'items',
      storeId: 'Task',
      });
store.load();

-----------------

But nothing works....

**Comment by kawanoshinobu** [comment]
Fmm..

I confirmed sample project "Ext.ux.AccordlingList/architect/accordionListSample.xda" with latest version of Architect. That works well.

Have you confirmed it? I have no idea about your problem..

**Comment by shailendramonu** [comment]
Sencha Architect
version: 3.0.4.1386
channel: 3.0.1-stable
platform: 1.3.0.803
cmd: 4.0.4.84
framework: Sencha Touch 2.3.x

I can see ajax request for json but cant see updating store.

<img width="1612" alt="screen shot 2015-09-14 at 3 34 15 pm" src="https://cloud.githubusercontent.com/assets/11848104/9842801/41c6fc90-5af6-11e5-9123-99bc9500f291.png">
<img width="1612" alt="screen shot 2015-09-14 at 3 34 29 pm" src="https://cloud.githubusercontent.com/assets/11848104/9842802/41c78e4e-5af6-11e5-975c-2806be96314d.png">
<img width="1249" alt="screen shot 2015-09-14 at 3 34 54 pm" src="https://cloud.githubusercontent.com/assets/11848104/9842800/41c705aa-5af6-11e5-9d71-72354bffeb92.png">
<img width="1240" alt="screen shot 2015-09-14 at 3 35 05 pm" src="https://cloud.githubusercontent.com/assets/11848104/9842805/41cda6ee-5af6-11e5-9d00-55799785df58.png">
<img width="1242" alt="screen shot 2015-09-14 at 3 35 12 pm" src="https://cloud.githubusercontent.com/assets/11848104/9842804/41ca0d2c-5af6-11e5-8eeb-d7a38028ee28.png">
<img width="1250" alt="screen shot 2015-09-14 at 3 35 20 pm" src="https://cloud.githubusercontent.com/assets/11848104/9842803/41c81288-5af6-11e5-8992-3adc974654d2.png">

**Comment by kawanoshinobu** [comment]
It seems that you don't set the store instance to the accordion list component. Let's try followings.

```
{
    xytpe: 'accordionlist',
    ...
    listeners: {
      fn: function (component, eOpts) {
          var store = Ext.create('MyApp.store.Task', {
              ...
          });
          store.load();
         // Sets store to the component
          component.setStore(store);
      },
      event: 'initialize'
   }
}

**Comment by shailendramonu** [comment]
Little change and store works. But in architect accordianlist needs to provide specific height, Its not working when not provide any height.
 
```javascript
{
    xytpe: 'accordionlist',
    ...
    listeners: {
      fn: function (component, eOpts) {
          var store = Ext.create('MyApp.store.Task', {
              ...
          });
          
         // Sets store to the component
          component.setStore(store);
          store.load();
      },
      event: 'initialize'
   }
}
```

**Comment by kawanoshinobu** [comment]
Have you tried to set 'layout:fit' at parent container? It would be required.
